config/routes.rb
Rails.application.routes.draw do
  # get 'event_attendances/create', to: 'event_attendances#create'
  # get 'event_attendances/destroy', to: 'event_attendances#destroy'
  # get 'event_attendances/update', to: 'event_attendances#update'
  devise_for :users
  root 'events#index'

  resources :events
  resources :event_attendances, only: [:create, :destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: 'creator_id'
  has_many :event_attendances, foreign_key: :attended_event_id
  has_many :attendees, through: :event_attendances, source: :attendee
end

app/models/event_attendance.rb
class EventAttendance < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :created_events, foreign_key: "creator_id", class_name: "Event"
  has_many :event_attendances, foreign_key: :attendee_id
  has_many :attended_events, through: :event_attendances, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_sign_up_params, only: [:create], if: :devise_controller?
  before_action :configure_account_update_params, only: [:update], if: :devise_controller?


  protected

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password)}
  end

  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
  end
end

app/controllers/event_attendances_controller.rb
class EventAttendancesController < ApplicationController
  def create
    @attendance = current_user.event_attendances.build(event_attendance_params)

    if @attendance.save
      flash[:success] = 'Great! See you at the event!'
      redirect_to @attendance
    else
      render :show, status: :unprocessable_entity
    end
  end

  def destroy
    @attendance = EventAttendance.find_by(attended_event_id: params[:id], attendee_id: current_user.id)
    @attendance.destroy

    flash[:success] = 'Your attendance has been cancelled'
    redirect_to event_path
  end
  
  private

  def event_attendance_params
    params.require(:event_attendance).permit(:attendee_id, :attended_event_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def show
    @attendance = EventAttendance.new
    @event = Event.find(params[:id])
  end

  def new
    @event = current_user.created_events.build
  end

  def create
    @event = current_user.created_events.build(event_params)

    if @event.save
      flash[:success] = 'Your event has been created!'
      redirect_to @event 
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    flash[:success] = 'Your event has been deleted!'

    redirect_to root_path, status: :see_other
  end

  private

  def event_params
    params.require(:event).permit(:name, :date, :creator_id)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendances_helper.rb
module EventAttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/event_attendances/create.html.erb
<div>
  <h1 class="font-bold text-4xl">EventAttendances#create</h1>
  <p>Find me in app/views/event_attendances/create.html.erb</p>
</div>

app/views/event_attendances/destroy.html.erb
<div>
  <h1 class="font-bold text-4xl">EventAttendances#destroy</h1>
  <p>Find me in app/views/event_attendances/destroy.html.erb</p>
</div>

app/views/event_attendances/update.html.erb
<div>
  <h1 class="font-bold text-4xl">EventAttendances#update</h1>
  <p>Find me in app/views/event_attendances/update.html.erb</p>
</div>

app/views/events/_all-events.html.erb
<div class="picked-events-container shadow-lg">
  <p class="font-bold" >All events currently online: </p>
  <ul class="flex flex-wrap">
    <% @events.each do |event| %>
      <li class="px-8 py-1 w-52 text-gray-300 hover:text-white hover:cursor-pointer transition"><%= link_to event.name, event_path(event) %></li>
    <% end %>
  </ul>
</div>

app/views/events/_attend.html.erb
<%= form_with model: @attendance do |form| %>
  <%= form.hidden_field :attended_event_id, :value => @event.id %>
  <%= form.hidden_field :attendee_id, :value => current_user.id %>
  <%= form.submit 'Attend', class: "btn-attendance-control" %>
<% end %>

app/views/events/_attendees.html.erb
<% unless @event.attendees.empty? %>
  <h2 class="font-bold">List of Attendees: </h2>
  <ul>
    <% @event.attendees.each do |attendee| %>
      <li><%= attendee.name %></li>
    <% end %>
  </ul>
<% end %>

app/views/events/_cancel.html.erb
<%= button_to 'Cancel Attendance', event_attendance_path, method: :delete, class: "btn-attendance-control" %>

app/views/events/_delete.html.erb
<%= link_to "Delete Event", event_path(@event), data: {
                                  turbo_method: :delete,
                                  turbo_confirm: "Are you sure?"
      }, class: "btn-attendance-control"%>

app/views/events/_header-block.html.erb
<div class="bg-blue-300 px-8 py-4 rounded-lg m-12 block w-[520px] self-center shadow-lg">
    <h1 class="text-white font-sans text-4xl font-extrabold">Eventual</h1>
      <% if user_signed_in? %>
        <h2 class="text-gray-100 italic font-semibold"><%= current_user.name %>'s personal events: </h2>
      <% else %>
        <h2 class="text-gray-100 italic font-semibold">Your personal guide in the world of happenings</h2>
      <% end %>
</div>

app/views/events/_time-dependent.html.erb
<div class="picked-events-container bg-orange-400 shadow-lg">
  <p class="font-bold" >All <b class="text-3xl font-extrabold">past</b> events: </p>
  <ul>
    <% @events.each do |event| %>
      <% if event.date < Date.today %>
        <li class="px-8 py-1 text-white hover:text-gray-100 hover:cursor-pointer transition"><%= link_to event.name, event_path(event) %></li>
      <% end %>
    <% end %>
  </ul>
  <p class="font-bold" >All <b class="text-3xl font-extrabold">upcoming</b> events: </p>
  <ul>
    <% @events.each do |event| %>
      <% if event.date > Date.today %>
        <li class="px-8 py-1 text-white hover:text-gray-100 hover:cursor-pointer transition"><%= link_to event.name, event_path(event) %></li>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/events/_users-events.html.erb
<div class="flex justify-between w-96 m-auto align-middle font-light">
  <% if user_signed_in? %>
    <ul class="mb-16">
      <li class="event-link hover:cursor-default hover:text-black font-bold mb-4" >Created Events</li>
      <% @events.each do |event| %>
        <% if event.creator == current_user %>
          <li class="event-link">
            <%= link_to event.name, event_path(event) %>
          </li>
        <% end %>
      <% end %>
    </ul>

    <ul>
      <li class="event-link hover:cursor-default hover:text-black font-bold mb-4">Events to Attend</li>
      <% current_user.attended_events.each do |attended_event| %>
        <li class="event-link"><%= link_to attended_event.name, event_path(attended_event) %></li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/events/index.html.erb
<div class="flex flex-col justify-center align-middle">
  <%= render 'header-block' %>
  <% if user_signed_in? %>
    <% unless current_user.attended_events.empty? && current_user.created_events.empty? %>
      <%= render 'users-events' %>
    <% else %>
      <p class="text-center font-extralight italic">Create or attend an event to keep track of them...</p>
    <% end %>
  <% else %>
    <p class="text-center font-extralight italic">Please sign in to be able to see your events</p>
  <% end %>
</div>

<%= render 'all-events' %>
<%= render 'time-dependent' %>

app/views/events/new.html.erb
<div class="wrapping-div" >
  <h1 class="font-bold text-3xl">New Event</h1>
  
  <%= form_with model: @event do |form| %>
    <div>
      <%= form.label :name %><br />
      <%= form.text_field :name %>
    </div>
  
    <div>
      <%= form.label :date %><br />
      <%= form.date_field :date %>
    </div>

    <div>
      <%= form.submit "Create Event", class: "btn-attendance-control" %>
    </div>
  
  <% end %>
</div>

app/views/events/show.html.erb
<div class="wrapping-div">
  <h1 class="font-bold text-3xl" ><%= @event.name %></h1>
  <div class="italic mb-5">Planned on: <%= @event.date.strftime('%B %-d, %Y') %></div>

  <% if user_signed_in? %>
      <ul>
        <li><%= render 'delete' %></li>
        <% if current_user.attended_events.include?(@event) %>
          <li><%= render 'cancel' %></li>
        <% else %>
          <li><%= render 'attend' %></li>
        <% end %>
      </ul>
        <div>
          <%= render 'attendees' %>
        </div>
  <% else %>
    <p>Please <%= link_to 'log in', new_user_session_path, class: "cursor:pointer underline hover:text-gray-300 transition"%> to be able to see the content</p>
  <% end %>
</div>

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <div class="block px-6 mt-[-2] text-blue-400" role="alert">
    <%= flash[:notice] %>
  </div>
<% elsif flash[:alert] %>
  <div class="block px-6 mt-[-2] text-red-400" role="alert">
    <%= flash[:alert] %>
  </div>
<% elsif flash[:success] %>
  <div class="block px-6 mt-[-2] text-blue-400">
    <%= flash[:success] %>
  </div>
<% else %>
  <div class="block px-6 mt-[-2] text-slate-50 h-6"></div>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="flex justify-between">
  <ul class="flex gap-5 px-6 pt-5">
  <li><%= link_to "Eventual", root_path, class: "text-blue-500 font-bold bg-blue-100 rounded-full p-3 hover:text-white hover:bg-blue-800 transition inline-block w-40 text-center" %></li>
    <% if current_user %>
      <li><%= link_to "Edit Account", edit_user_registration_path, class: "btn-navbar" %></li>
      <li><%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn-navbar" %></li>
      <li><%= link_to "Add Event", new_event_path, class: "btn-navbar"%></li>
    <% else %>
      <li><%= link_to "Sign Up", new_user_registration_path, class: "btn-navbar"%></li>
      <li><%= link_to "Sign In", new_user_session_path, class: "btn-navbar"%></li>
    <% end %>
  </ul>
  <p class="px-6 pt-5">by <a href="https://github.com/Rattlehead90" class="group animate-pulse hover:animate-none underline hover:text-white hover:ml-8 hover:no-underline hover:bg-indigo-400 hover:p-2 hover:rounded-lg transition-all decoration-sky-500 ">Rattlehead90 <span class="absolute ml-[-9rem] group-hover:scale-100 scale-0 transition-all align-middle"><%= image_tag "github.png", style: 'width: 20px;' %></span> </a>, 2022</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,300;0,500;0,800;1,200&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-slate-50">
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/flash' %>
      <main class="container font-noto mx-auto px-5">
        <%= yield %>
      </main>
  </body>
</html>